<?php

require_once DRUPAL_ROOT . '/' . variable_get('password_inc', 'includes/password.inc');

function modifier_password_menu() {
    $items['modifier-my-password'] = array('title' => t("Modif Password"),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('modifier_password_form'),
        'access arguments' => array('modifier_password'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function modifier_password_permission() {
    return array(
        'modifier_password' => array(
            'title' => t('acces au page modification mps'),
            'restrict access' => TRUE,
            ));
}

function modifier_password_form($form, &$form_state) {
    global $user;
    $form['#account'] = $user;
    $form['#prefix'] = '<div class="bloc-under-container">';
    $form['#attributes']['class'] = array('inscri-form');
    $form['#suffix'] = '</div>';
    $form['mail'] = array(
        '#type' => 'textfield',
        '#title' => t('mail'),
        '#default_value' => $user->mail,
        '#size' => 60,
        '#attributes' => array('placeholder' => t('mail')),
        '#maxlength' => 128,
        '#required' => TRUE,
    );

    $form['pass_current'] = array(
        '#type' => 'password',
        '#title' => t('Current Password'),
        '#attributes' => array('placeholder' => t('Current Password')),
        '#maxlength' => 64,
        '#size' => 15,
        '#required' => TRUE,
    );
    $form['pass'] = array(
        '#type' => 'password_confirm',
        '#title' => t('Password'),
        '#size' => 25,
    );
    $form['submit'] = array(
        '#value' => 'Submit',
        '#type' => 'submit',
        '#value' => 'send',
        '#attributes' => array('class' => array('info-btn'))
    );
    return $form;
}

function modifier_password_form_validate(&$form, &$form_state) {
    global $user;
    $currentpsws = $form_state['values']['pass_current'];
    $email = $form_state['values']['mail'];
    $existingUser = user_load($user->uid);
    if (!preg_match('/^([a-zA-Z0-9])+([a-zA-Z0-9\._-])*@([a-zA-Z0-9_-])+([a-zA-Z0-9\._-]+)+$/', (string) $email)) {
        form_set_error('mail', t("@name adress email not valid", array('@name' => $email)));
    } elseif (($email != $user->mail) && user_load_by_mail($email)) {
        form_set_error('mail', 'Email user is already exsist');
    }


    if (!user_check_password($currentpsws, $form['#account'])) {
        form_set_error('current_pass', t('The current password you provided is incorrect.'));
    }
}

function modifier_password_form_submit(&$form, $form_state) {
    global $user;
    $existingUser = user_load($user->uid);
    $existingUser->mail = $form_state ['values']['mail'];
    $existingUser->init = $form_state['values']['mail'];
    if (!empty($form_state['values']['pass'])) {
        $existingUser->pass = user_hash_password($form_state['values']['pass']);
    }
    user_save($existingUser);
}

?>